/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\MotionProfiles.c
 *  model: MassSpringDamper
 *  expmt: MassSpringDamper
 *  date:  April 3, 2017
 *  time:  11:26:43 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

