/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\motionprofiles.c
 *  model: WaterTankCascade
 *  expmt: WaterTankCascade
 *  date:  October 30, 2015
 *  time:  12:29:45 pm
 *  user:  INTO-CPS
 *  from:  20-sim 4.5 Professional Single
 *  build: 4.5.1.5561
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

