/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.c
 *  subm:  MassSpringDamper1
 *  model: MassSpringDamper
 *  expmt: MassSpringDamper
 *  date:  April 3, 2017
 *  time:  11:26:28 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxinteg.h"
#include "xxfuncs.h"
#include "xxsubmod.h"
#include "MotionProfiles.h"
#include "EulerAngles.h"


/* The initialization function for submodel */
void XXInitializeSubmodel (xx_ModelInstance* model_instance)
{
	/* Initialization phase (allocating memory) */
	model_instance->initialize = XXTRUE;
	model_instance->steps = 0;
	XXRungeKutta4Initialize (model_instance);

	/* Calculate the model for the first time */
	XXCalculateInitial (model_instance);
	XXCalculateStatic (model_instance);
	XXCalculateInput (model_instance);
	XXCalculateDynamic (model_instance);
	XXCalculateOutput (model_instance);

	/* End of initialization phase */
	model_instance->initialize = XXFALSE;
}

/* The function that calculates the submodel */
void XXCalculateSubmodel (xx_ModelInstance* model_instance, XXDouble t)
{
	/* Copy the time */
	model_instance->time = t;

	/* Calculate the model */
	XXCalculateInput (model_instance);
	XXRungeKutta4Step (model_instance);
	XXCalculateOutput (model_instance);
}

/* The termination function for submodel */
void XXTerminateSubmodel (xx_ModelInstance* model_instance, XXDouble t)
{
	/* Copy the time */
	model_instance->time = t;

	/* Calculate the final model equations */
	XXCalculateFinal (model_instance);

	/* and terminate the model itself (releasing memory) */
	XXModelTerminate (model_instance);
	XXRungeKutta4Terminate (model_instance);
}

