/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxinverse.c
 *  model: WaterTankCascade
 *  expmt: WaterTankCascade
 *  date:  October 30, 2015
 *  time:  12:29:28 pm
 *  user:  INTO-CPS
 *  from:  20-sim 4.5 Professional Single
 *  build: 4.5.1.5561
 **********************************************************/

/* No matrix support functions are needed for this model */

